### ISSUE TITLE
GNU Go opponent currently down (govsgo.com)

### ISSUE THREAD

**Issue by shimari** [ryanb/govsgo#39]
The computer opponent is currently unresponsive on the main site.

**Comment by ryanb** [comment]
Thank you for reporting this. It looks like the background process died which handles the computer moves. It is back up now, but I'll leave this ticket open until I set up some kind of process monitor to ensure it stays up.

**Comment by shimari** [comment]
It's down again.

**Comment by ryanb** [comment]
Very strange. Thanks for reporting. I've started it up again.

**Comment by shimari** [comment]
It's currently down again.

**Comment by ryanb** [comment]
Sorry about that, thanks for reporting this. Should be up again. Really need to figure out what's causing this.

**Comment by ryanb** [comment]
Looks like this time the actual process stayed up but the MySQL connection timed out. I should probably set up a cron task to occasionally restart long running processes like this.

**Comment by shimari** [comment]
Needs a restart again.

**Comment by ryanb** [comment]
Thanks. Sorry for the delays in fixing this.

**Comment by ryanb** [comment]
I've set up god for monitoring the process. I've also made it so it automatically reconnects to the MySQL database if it loses its connection. This should solve this issue, but if it ever goes down again please post a comment here.
