### ISSUE TITLE
Unable to sign in through FB

### ISSUE THREAD

**Issue by AsemRadhwi** [ryanb/govsgo#45]
I am trying to sign in using facebook, but I got this weird message:
Change Rejected (422)

The change you wanted was rejected. Maybe you tried to change something you didn't have access to.

**Comment by ryanb** [comment]
Sorry for not getting back to you sooner on this. Facebook sign in is working for me, perhaps it is a temporary problem. Can you try it again and let me know if it is still not working? Thanks.

**Comment by AsemRadhwi** [comment]
Ryan,
Still the same issue:

Change Rejected (422)

The change you wanted was rejected. Maybe you tried to change something you didn't have access to.

**Comment by ryanb** [comment]
Thanks for trying this out again, I'll look into this problem some more.
