### ISSUE TITLE
Error 500 creating a new game

### ISSUE THREAD

**Issue by coleki** [ryanb/govsgo#54]
Hi!

When creating a new game against the computer on a 9x9 board, after I clck the create button, the website gives me a 500 error with a "sorry, something went wrong" message.

This started happening just recently; today (6/30/2011) or yesterday...?

When I browse back to the main page, the game actually appears, so I can play it normally after that.

I am on an HTC Evo, Froyo 2.2, running the Miren browser.

Just thought I'd let you know! Also, getting a move confirmation feature for those of us using touchscreens would be awesome!

Thanks for making such an awesome platform!
-coleki

**Comment by ryanb** [comment]
Thanks for reporting this. I'll look into it as soon as I get a chance.

**Comment by ryanb** [comment]
This should be fixed now, please let me know if you come across any other problems.

**Comment by coleki** [comment]
I just retested, and no error! Thanks!
On Jul 1, 2011 3:24 PM, "ryanb" <
reply@reply.github.com>
wrote:
